apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-operators
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/RedHat-Summit-Connect-France-2023/janus-gitops.git
    targetRevision: main
    path: gitops/cluster-operators/base
  destination:
    server: https://kubernetes.default.svc
    #namespace: backstage
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      selfHeal: false
      prune: false
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
